### ISSUE TITLE
questions

### ISSUE THREAD

**Issue by wynotlike** [Wanderlust717/CARGNet#1]
D:\anaconda\envs\wypytorch\python.exe D:\python-project\pythonProject6\CARGNet-main\train.py 
D:\anaconda\envs\wypytorch\lib\site-packages\scipy\__init__.py:146: UserWarning: A NumPy version >=1.16.5 and <1.23.0 is required for this version of SciPy (detected version 1.24.4
  warnings.warn(f"A NumPy version >={np_minversion} and <{np_maxversion}"
Traceback (most recent call last):
  File "D:\python-project\pythonProject6\CARGNet-main\train.py", line 501, in <module>
    main()
  File "D:\python-project\pythonProject6\CARGNet-main\train.py", line 411, in main
    args = options.parse()
  File "D:\python-project\pythonProject6\CARGNet-main\options.py", line 35, in parse
    os.makedirs('%s' % ( args.img_result_dir), exist_ok=True)
AttributeError: 'Namespace' object has no attribute 'img_result_dir'

**Comment by gosling123456** [comment]
> D:\anaconda\envs\wypytorch\python.exe D:\python-project\pythonProject6\CARGNet-main\train.py D:\anaconda\envs\wypytorch\lib\site-packages\scipy__init__.py:146: UserWarning: A NumPy version >=1.16.5 and <1.23.0 is required for this version of SciPy (detected version 1.24.4 warnings.warn(f"A NumPy version >={np_minversion} and <{np_maxversion}" Traceback (most recent call last): File "D:\python-project\pythonProject6\CARGNet-main\train.py", line 501, in main() File "D:\python-project\pythonProject6\CARGNet-main\train.py", line 411, in main args = options.parse() File "D:\python-project\pythonProject6\CARGNet-main\options.py", line 35, in parse os.makedirs('%s' % ( args.img_result_dir), exist_ok=True) AttributeError: 'Namespace' object has no attribute 'img_result_dir'

add a new parameter by :
self.parser.add_argument('--img_result_dir', type=str, default='data/LEVIR-CD-Point', help=' where to save the checkpoints')
